# Generated by Django 4.2 on 2023-04-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_token',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
