# Generated by Django 4.2.3 on 2023-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_todaysnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='google_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
